# If you are using the systemd hook, it will not work; this file is ideal, you don't need to modify your mkinitcpio.conf.
MODULES=(overlay)

HOOKS=(base udev autodetect modconf kms keyboard keymap block overlay-preview)

COMPRESSION="zstd"
